### ISSUE TITLE
TODO List

### ISSUE THREAD

**Issue by towa0131** [DragonBox-Network/DragonBox-Application-Desktop#1]
- [ ] Show Player Status
- [ ] User Login
- [x] Check Server Status
- [ ] Chat System
- [ ] Auto Update System
- [ ] Change Config System
